spring:
  application:
    name: ead-authuser-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-service
      username: configServer
      password: 'ead123cs'